post:
  summary: 执行ansibleplaybook
  description: |
    调用成功后

     - start_time将置为当前时间
     - end_time置为空
     - status设置为running
  parameters:
    - $ref: "../parameters/ansibleplaybook.yaml#/ansibleplaybookId"
    - name: ansibleplaybook
      in: body
      schema:
        $ref: "../schemas/ansibleplaybook.yaml#/AnsiblePlaybookCreateRequest"
  responses:
    200:
      description: ansibleplaybook的信息
      schema:
        $ref: "../schemas/ansibleplaybook.yaml#/AnsiblePlaybookResponse"
  tags:
    - ansibleplaybooks
