get:
  summary: 按指定条件列出ansibleplaybook实例
  responses:
    200:
      description: 实例列表信息
      schema:
        $ref: "../schemas/ansibleplaybook.yaml#/AnsiblePlaybookListResponse"
  tags:
    - ansibleplaybooks
post:
  summary: 创建ansibleplaybook实例
  parameters:
    - name: ansibleplaybook
      in: body
      schema:
        $ref: "../schemas/ansibleplaybook.yaml#/AnsiblePlaybookCreateRequest"
  responses:
    200:
      description: 新创建的实例信息
      schema:
        $ref: "../schemas/ansibleplaybook.yaml#/AnsiblePlaybookResponse"
  tags:
    - ansibleplaybooks
