get:
  summary: 按指定条件列出宿主机
  parameters:
    - $ref: '../parameters/common.yaml#/limit'
    - $ref: '../parameters/common.yaml#/offset'
    - $ref: '../parameters/common.yaml#/provider'
    - $ref: '../parameters/common.yaml#/zone'
    - $ref: '../parameters/common.yaml#/wire'
    - $ref: '../parameters/common.yaml#/vpc'
    - $ref: '../parameters/common.yaml#/region'
    - $ref: '../parameters/host.yaml#/enable'
    - $ref: '../parameters/host.yaml#/disable'
    - $ref: '../parameters/host.yaml#/host_type'
    - $ref: '../parameters/host.yaml#/is_empty'
    - $ref: '../parameters/host.yaml#/storage'
    - $ref: '../parameters/host.yaml#/usable'
    - $ref: '../parameters/host.yaml#/hypervisor'
    - $ref: '../parameters/host.yaml#/any_mac'
    - $ref: '../parameters/host.yaml#/cachedimage'
    - $ref: '../parameters/host.yaml#/is_baremetal'
    - $ref: '../parameters/host.yaml#/resource_type'
    - $ref: '../parameters/host.yaml#/storage_not_attached'
  responses:
    200:
      description: 宿主机列表信息
      schema:
        $ref: '../schemas/host.yaml#/HostListResponse'
  tags:
    - host
post:
  summary: 注册物理机
  parameters:
    - in: body
      name: host
      required: true
      schema:
        $ref: '../schemas/host.yaml#/HostCreate' 
  responses:
    200:
      description: 新创建的宿主机信息
      schema:
        $ref: '../schemas/host.yaml#/HostResponse'
  tags:
    - host